# Generated by Django 4.1.3 on 2022-12-03 11:29

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street", models.CharField(max_length=100, verbose_name="Steet")),
                (
                    "post_code",
                    models.CharField(max_length=6, verbose_name="Postal Code"),
                ),
                ("city", models.CharField(max_length=100, verbose_name="City")),
                ("country", models.CharField(max_length=100, verbose_name="Country")),
                (
                    "lng",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        max_digits=9,
                        verbose_name="Longitude",
                    ),
                ),
                (
                    "lat",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        max_digits=9,
                        verbose_name="Latitude",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WishList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                ("email", models.EmailField(max_length=100, verbose_name="E-mail")),
                ("content", models.TextField(max_length=1000, verbose_name="Content")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "NEW"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                            ("READY_FOR_SHIPPING", "Ready for shipping"),
                            ("DELIVERED", "Delivered"),
                        ],
                        default="NEW",
                        max_length=100,
                        verbose_name="Status",
                    ),
                ),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True, editable=False, populate_from="name"
                    ),
                ),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wishes.address",
                        verbose_name="Address",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WishListItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "approved",
                    models.BooleanField(default=False, verbose_name="Approved"),
                ),
                (
                    "wish_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wishes.wishlist",
                        verbose_name="Wish List",
                    ),
                ),
            ],
        ),
    ]
